# Настройки сервера
server.port=8080
server.tomcat.max-threads=100000
server.tomcat.accept-count=100000
server.tomcat.max-connections=100000

# Предотвращаем завершение приложения
spring.main.web-application-type=servlet

# Настройки логирования
logging.level.root=ERROR
logging.level.com.srg.test=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Настройки нагрузочного теста
load.test.enabled=false
load.test.threads=10000
load.test.depth=5
load.test.delay.ms=3000

# Увеличиваем таймауты для RestTemplate
spring.mvc.async.request-timeout=120000

# Настройки пула потоков
app.thread-model=virtual
app.thread-count=24
app.async-nio=false